/**
 * Catalogo central de `data-testid`.
 *
 * Convencion: `<feature>-<elemento>-<rol>`, en minusculas y con guiones.
 *
 * Estos identificadores son CONTRATO: se tratan como API publica de la interfaz.
 * No se renombran sin anotarlo en docs/testids.md, porque la automatizacion de
 * pruebas depende de ellos.
 *
 * Este archivo NO contiene pruebas. La automatizacion se desarrolla aparte.
 */
export const testIds = {
  layout: {
    appShell: 'layout-app-shell',
    sidebar: 'layout-sidebar',
    sidebarToggle: 'layout-sidebar-toggle',
    header: 'layout-header',
    themeToggle: 'layout-theme-toggle',
    navItem: (key: string) => `layout-nav-${key}`,
    navBadge: (key: string) => `layout-nav-badge-${key}`,
    pageTitle: 'layout-page-title',
  },

  state: {
    loading: 'state-loading',
    empty: 'state-empty',
    error: 'state-error',
    errorRetry: 'state-error-retry',
  },

  toast: {
    root: 'toast-root',
  },

  ads: {
    slot: 'ads-slot',
    placeholder: 'ads-placeholder',
  },

  confirm: {
    dialog: 'confirm-dialog',
    accept: 'confirm-accept',
    cancel: 'confirm-cancel',
  },

  auth: {
    bootSplash: 'auth-boot-splash',
    loginPage: 'auth-login-page',
    registerPage: 'auth-register-page',
    nameInput: 'auth-name-input',
    emailInput: 'auth-email-input',
    passwordInput: 'auth-password-input',
    submitButton: 'auth-submit-button',
    formError: 'auth-form-error',
    goToRegister: 'auth-go-to-register',
    goToLogin: 'auth-go-to-login',
    forgotPasswordPage: 'auth-forgot-password-page',
    resetLinkSent: 'auth-reset-link-sent',
    resetPasswordPage: 'auth-reset-password-page',
    invalidResetLink: 'auth-invalid-reset-link',
    requestNewLink: 'auth-request-new-link',
    goToForgotPassword: 'auth-go-to-forgot-password',
    currentPasswordInput: 'auth-current-password-input',
    newPasswordInput: 'auth-new-password-input',
    confirmPasswordInput: 'auth-confirm-password-input',
    loginNotice: 'auth-login-notice',
    userMenu: 'auth-user-menu',
    userName: 'auth-user-name',
    logoutButton: 'auth-logout-button',
  },

  settings: {
    page: 'settings-page',
    email: 'settings-email',
    systemCard: 'settings-system-card',
    systemStatus: 'settings-system-status',
    systemVersion: 'settings-system-version',
    cycleCard: 'settings-cycle-card',
    cycleType: 'settings-cycle-type',
    cycleAnchor: 'settings-cycle-anchor',
    cycleSubmit: 'settings-cycle-submit',
    cycleError: 'settings-cycle-error',
    themeCard: 'settings-theme-card',
    themeOption: (value: string) => `settings-theme-${value}`,
    changePasswordCard: 'settings-change-password-card',
    changePasswordSubmit: 'settings-change-password-submit',
    changePasswordError: 'settings-change-password-error',
  },

  incomes: {
    page: 'incomes-page',
    createButton: 'incomes-create-button',
    list: 'incomes-list',
    row: (id: string) => `incomes-row-${id}`,
    rowName: 'incomes-row-name',
    rowAmount: 'incomes-row-amount',
    rowType: 'incomes-row-type',
    rowSchedule: 'incomes-row-schedule',
    rowInactive: 'incomes-row-inactive',
    rowReview: 'incomes-row-review',
    rowMenu: 'incomes-row-menu',
    editAction: 'incomes-action-edit',
    toggleActiveAction: 'incomes-action-toggle-active',
    deleteAction: 'incomes-action-delete',

    filterType: 'incomes-filter-type',
    filterActive: 'incomes-filter-active',
    sort: 'incomes-sort',
    pagination: 'incomes-pagination',

    drawer: 'incomes-drawer',
    drawerTitle: 'incomes-drawer-title',
    nameInput: 'incomes-name-input',
    typeInput: 'incomes-type-input',
    amountInput: 'incomes-amount-input',
    frequencyInput: 'incomes-frequency-input',
    expectedDayInput: 'incomes-expected-day-input',
    startDateInput: 'incomes-start-date-input',
    endDateInput: 'incomes-end-date-input',
    notesInput: 'incomes-notes-input',
    reviewNotice: 'incomes-review-notice',
    submitButton: 'incomes-submit-button',
    cancelButton: 'incomes-cancel-button',
    formError: 'incomes-form-error',
  },

  expenses: {
    page: 'expenses-page',
    createButton: 'expenses-create-button',
    list: 'expenses-list',
    row: (id: string) => `expenses-row-${id}`,
    rowName: 'expenses-row-name',
    rowAmount: 'expenses-row-amount',
    rowCategory: 'expenses-row-category',
    rowSchedule: 'expenses-row-schedule',
    rowFlexibility: 'expenses-row-flexibility',
    rowInactive: 'expenses-row-inactive',
    rowReview: 'expenses-row-review',
    rowMenu: 'expenses-row-menu',
    editAction: 'expenses-action-edit',
    toggleActiveAction: 'expenses-action-toggle-active',
    deleteAction: 'expenses-action-delete',

    filterKind: 'expenses-filter-kind',
    filterCategory: 'expenses-filter-category',
    filterActive: 'expenses-filter-active',
    sort: 'expenses-sort',
    pagination: 'expenses-pagination',

    drawer: 'expenses-drawer',
    drawerTitle: 'expenses-drawer-title',
    nameInput: 'expenses-name-input',
    kindInput: 'expenses-kind-input',
    amountInput: 'expenses-amount-input',
    categoryInput: 'expenses-category-input',
    flexibilityInput: 'expenses-flexibility-input',
    frequencyInput: 'expenses-frequency-input',
    dueDayInput: 'expenses-due-day-input',
    startDateInput: 'expenses-start-date-input',
    endDateInput: 'expenses-end-date-input',
    notesInput: 'expenses-notes-input',
    reviewNotice: 'expenses-review-notice',
    criticalNotice: 'expenses-critical-notice',
    submitButton: 'expenses-submit-button',
    cancelButton: 'expenses-cancel-button',
    formError: 'expenses-form-error',
  },

  onboarding: {
    page: 'onboarding-page',
    stepper: 'onboarding-stepper',
    step: (key: string) => `onboarding-step-${key}`,
    nextButton: 'onboarding-next',
    backButton: 'onboarding-back',
    skipStepButton: 'onboarding-skip-step',
    skipAllButton: 'onboarding-skip-all',
    finishButton: 'onboarding-finish',
    error: 'onboarding-error',

    cycleTypeInput: 'onboarding-cycle-type',
    cycleAnchorInput: 'onboarding-cycle-anchor',
    cyclePreview: 'onboarding-cycle-preview',

    incomeName: 'onboarding-income-name',
    incomeAmount: 'onboarding-income-amount',
    incomeType: 'onboarding-income-type',
    incomeFrequency: 'onboarding-income-frequency',
    incomeDay: 'onboarding-income-day',
    incomeAdd: 'onboarding-income-add',
    incomeList: 'onboarding-income-list',
    incomeRow: 'onboarding-income-row',

    categoryChip: (code: string) => `onboarding-category-${code}`,
    expenseAmount: 'onboarding-expense-amount',
    expenseList: 'onboarding-expense-list',
    expenseRow: 'onboarding-expense-row',
    expenseCustomName: 'onboarding-expense-custom-name',

    goalName: 'onboarding-goal-name',
    goalTarget: 'onboarding-goal-target',
    goalPerCycle: 'onboarding-goal-per-cycle',
    goalAdd: 'onboarding-goal-add',
    goalList: 'onboarding-goal-list',

    summaryIncomes: 'onboarding-summary-incomes',
    summaryExpenses: 'onboarding-summary-expenses',
    summaryGoals: 'onboarding-summary-goals',
    summaryCycle: 'onboarding-summary-cycle',
  },

  review: {
    page: 'review-page',
    cycleRange: 'review-cycle-range',
    list: 'review-list',
    row: (id: string) => `review-row-${id}`,
    rowName: 'review-row-name',
    rowPlanned: 'review-row-planned',
    rowAmountInput: 'review-row-amount-input',
    rowSuggestion: 'review-row-suggestion',
    rowUseSuggestion: 'review-row-use-suggestion',
    rowHistory: 'review-row-history',
    confirmAllButton: 'review-confirm-all',
    confirmedCount: 'review-confirmed-count',
    formError: 'review-form-error',

    historyDialog: 'review-history-dialog',
    historyRow: 'review-history-row',
    historyEmpty: 'review-history-empty',
    historyAverage: 'review-history-average',

    savingsSection: 'review-savings-section',
    savingsRow: (id: string) => `review-savings-row-${id}`,
    savingsSettleAction: 'review-savings-settle',
    settleDialog: 'review-settle-dialog',
    settleAmount: 'review-settle-amount',
    settleDate: 'review-settle-date',
    settleSkipGoal: 'review-settle-skip-goal',
    settleSubmit: 'review-settle-submit',
    settleError: 'review-settle-error',
  },

  savings: {
    page: 'savings-page',
    createButton: 'savings-create-button',
    list: 'savings-list',
    card: (id: string) => `savings-card-${id}`,
    cardName: 'savings-card-name',
    cardProgress: 'savings-card-progress',
    cardProgressBar: 'savings-card-progress-bar',
    cardSaved: 'savings-card-saved',
    cardRemaining: 'savings-card-remaining',
    cardPerCycle: 'savings-card-per-cycle',
    cardStatus: 'savings-card-status',
    cardMenu: 'savings-card-menu',
    dragHandle: 'savings-drag-handle',
    moveUp: 'savings-move-up',
    moveDown: 'savings-move-down',

    editAction: 'savings-action-edit',
    contributeAction: 'savings-action-contribute',
    withdrawAction: 'savings-action-withdraw',
    pauseAction: 'savings-action-pause',
    movementsAction: 'savings-action-movements',
    deleteAction: 'savings-action-delete',

    filterStatus: 'savings-filter-status',

    drawer: 'savings-drawer',
    drawerTitle: 'savings-drawer-title',
    nameInput: 'savings-name-input',
    targetInput: 'savings-target-input',
    modeInput: 'savings-mode-input',
    targetDateInput: 'savings-target-date-input',
    perCycleInput: 'savings-per-cycle-input',
    submitButton: 'savings-submit-button',
    cancelButton: 'savings-cancel-button',
    formError: 'savings-form-error',

    movementDialog: 'savings-movement-dialog',
    movementAmount: 'savings-movement-amount',
    movementDate: 'savings-movement-date',
    movementNotes: 'savings-movement-notes',
    movementSubmit: 'savings-movement-submit',
    movementError: 'savings-movement-error',

    movementsDrawer: 'savings-movements-drawer',
    movementRow: 'savings-movement-row',
    movementsEmpty: 'savings-movements-empty',
  },

  notifications: {
    bell: 'notifications-bell',
    badge: 'notifications-badge',
    menu: 'notifications-menu',
    list: 'notifications-list',
    row: (id: string) => `notifications-row-${id}`,
    empty: 'notifications-empty',
    markAllRead: 'notifications-mark-all-read',
  },

  dashboard: {
    page: 'dashboard-page',
    greeting: 'dashboard-greeting',

    cycleRange: 'dashboard-cycle-range',
    openCycleButton: 'dashboard-open-cycle',
    closeCycleButton: 'dashboard-close-cycle',

    hero: 'dashboard-hero',
    heroAmount: 'dashboard-hero-amount',
    heroHeadline: 'dashboard-hero-headline',
    heroDetail: 'dashboard-hero-detail',
    heroEstimateNotice: 'dashboard-hero-estimate-notice',

    composition: 'dashboard-composition',
    compositionBar: 'dashboard-composition-bar',
    compositionSegment: (key: string) => `dashboard-composition-${key}`,
    totalIncome: 'dashboard-total-income',
    totalFixed: 'dashboard-total-fixed',
    totalVariable: 'dashboard-total-variable',
    totalSavings: 'dashboard-total-savings',
    savingsRate: 'dashboard-savings-rate',

    upcoming: 'dashboard-upcoming',
    upcomingRow: 'dashboard-upcoming-row',
    upcomingOverdue: 'dashboard-upcoming-overdue',
    upcomingEmpty: 'dashboard-upcoming-empty',
    settleAction: 'dashboard-settle-action',

    reviewNotice: 'dashboard-review-notice',

    advice: 'dashboard-advice',
    adviceRow: 'dashboard-advice-row',
    adviceShortfall: 'dashboard-advice-shortfall',
    adviceSkipAction: 'dashboard-advice-skip',

    trend: 'dashboard-trend',
    trendChart: 'dashboard-trend-chart',
    trendDelta: 'dashboard-trend-delta',
    trendEmpty: 'dashboard-trend-empty',
  },
} as const;
